export const appTypes = {
  CITY: 'CITY',
  CITY_SUCCESS: 'CITY_SUCCESS',
  CITY_FAILURE: ' CITY_FAILURE',
  FIVE_DAY: 'FIVE_DAY',
  FIVE_DAY_FAILED: 'FIVE_DAY_FAILED',
  FIVE_DAY_SUCCESS: 'FIVE_DAY_SUCCESS',
  SET_CURRENT_DAY: 'SET_CURRENT_DAY',
};
